Repository discretize/discretize-guides, pull requests merged in 2022-01, with the labels that each got.

#744 Update Builds “revenant/power-renegade/index”
  builds/revenant/power-renegade/index.md
Labels: netlify-cms/draft

#745 Update Builds “revenant/power-renegade/index”
  builds/revenant/power-renegade/index.md
Labels: netlify-cms/draft

#746 Update Builds “revenant/condi-alac-renegade/index”
  builds/revenant/condi-alac-renegade/index.md
Labels: netlify-cms/draft

#748 Update Builds “revenant/power-renegade/index”
  builds/revenant/power-renegade/index.md
Labels: netlify-cms/pending_publish

#751 Update Builds “elementalist/power-weaver/index”
  builds/elementalist/power-weaver/index.md
Labels: netlify-cms/pending_publish

#752 Update Builds “engineer/power-holosmith/index”
  builds/engineer/power-holosmith/index.md
Labels: netlify-cms/pending_publish

#753 Update Builds “guardian/heal-firebrand/index”
  builds/guardian/heal-firebrand/index.md
Labels: netlify-cms/pending_publish

#754 Update Builds “guardian/heal-firebrand/index”
  builds/guardian/heal-firebrand/index.md
Labels: netlify-cms/pending_publish

#756 Update Builds “guardian/power-firebrand/index”
  builds/guardian/power-firebrand/index.md
Labels: netlify-cms/pending_publish

#757 Update Builds “guardian/condi-firebrand/index”
  builds/guardian/condi-firebrand/index.md
Labels: netlify-cms/pending_publish

#758 Update Builds “guardian/power-dragonhunter/index”
  builds/guardian/power-dragonhunter/index.md
Labels: netlify-cms/pending_publish

#759 Update Builds “guardian/seraph-firebrand/index”
  builds/guardian/seraph-firebrand/index.md
Labels: netlify-cms/pending_publish

#760 Update Builds “mesmer/power-chronomancer/index”
  builds/mesmer/power-chronomancer/index.md
Labels: netlify-cms/pending_publish

#763 Update Builds “necromancer/condi-scourge/index”
  builds/necromancer/condi-scourge/index.md
Labels: netlify-cms/pending_publish

#765 Update Builds “necromancer/power-reaper/index”
  builds/necromancer/power-reaper/index.md
Labels: netlify-cms/pending_publish

#768 Update Builds “ranger/condi-soulbeast/index”
  builds/ranger/condi-soulbeast/index.md
Labels: netlify-cms/pending_publish

#769 Update Builds “ranger/power-soulbeast/index”
  builds/ranger/power-soulbeast/index.md
Labels: netlify-cms/pending_publish

#770 Update CM-Guides “guardian/power-dragonhunter/index”
  cm-guides/guardian/power-dragonhunter/index.md
Labels: netlify-cms/pending_publish

#780 Update Guides “crit-cap/index”
  guides/crit-cap/index.md
Labels: netlify-cms/pending_publish

#772 Update Builds “elementalist/power-weaver/index”
  builds/elementalist/power-weaver/index.md
Labels: netlify-cms/pending_publish

#779 Update Builds “necromancer/condi-scourge/index”
  builds/necromancer/condi-scourge/index.md
Labels: netlify-cms/pending_publish

#771 Update Builds “elementalist/condi-weaver/index”
  builds/elementalist/condi-weaver/index.md
Labels: netlify-cms/pending_publish

#774 Update Builds “guardian/power-firebrand/index”
  builds/guardian/power-firebrand/index.md
Labels: netlify-cms/pending_publish

#777 Update Builds “guardian/seraph-firebrand/index”
  builds/guardian/seraph-firebrand/index.md
Labels: netlify-cms/pending_publish

#775 Update Builds “guardian/condi-firebrand/index”
  builds/guardian/condi-firebrand/index.md
Labels: netlify-cms/pending_publish

#776 Update Builds “guardian/power-dragonhunter/index”
  builds/guardian/power-dragonhunter/index.md
Labels: netlify-cms/pending_publish

#783 Update Builds “ranger/power-soulbeast/index”
  builds/ranger/power-soulbeast/index.md
Labels: netlify-cms/pending_publish

#778 Update Builds “mesmer/power-chronomancer/index”
  builds/mesmer/power-chronomancer/index.md
Labels: netlify-cms/pending_publish

#781 Update Builds “revenant/condi-alac-renegade/index”
  builds/revenant/condi-alac-renegade/index.md
Labels: netlify-cms/pending_publish

#782 Update Builds “ranger/condi-soulbeast/index”
  builds/ranger/condi-soulbeast/index.md
Labels: netlify-cms/pending_publish

#784 Update Builds “thief/condi-deadeye/index”
  builds/thief/condi-deadeye/index.md
Labels: netlify-cms/pending_publish

#773 Update Builds “guardian/heal-firebrand/index”
  builds/guardian/heal-firebrand/index.md
Labels: netlify-cms/pending_publish

#785 Update Builds “warrior/power-berserker/index”
  builds/warrior/power-berserker/index.md
Labels: netlify-cms/pending_publish

#788 Update Builds “guardian/heal-firebrand/index”
  builds/guardian/heal-firebrand/index.md
Labels: netlify-cms/pending_publish

#790 Update Guides “meta-explained/index”
  guides/meta-explained/index.md
Labels: netlify-cms/pending_publish

#789 Update Guides “what-should-i-play/index”
  guides/what-should-i-play/index.md
Labels: netlify-cms/pending_publish

#794 Update CM-Guides “warrior/power-berserker/static”
  cm-guides/warrior/power-berserker/static.md
Labels: netlify-cms/pending_publish

#797 Update CM-Guides “ranger/power-soulbeast/static”
  cm-guides/ranger/power-soulbeast/static.md
Labels: netlify-cms/pending_publish

#796 Update CM-Guides “guardian/power-dragonhunter/index”
  cm-guides/guardian/power-dragonhunter/index.md
Labels: netlify-cms/pending_publish

#793 Update Builds “revenant/power-renegade/index”
  builds/revenant/power-renegade/index.md
Labels: netlify-cms/pending_publish

#795 Update CM-Guides “revenant/power-renegade/static”
  cm-guides/revenant/power-renegade/static.md
Labels: netlify-cms/pending_publish

#799 Update Builds “elementalist/condi-weaver/index”
  builds/elementalist/condi-weaver/index.md
Labels: netlify-cms/pending_publish

#802 Update Builds “ranger/power-soulbeast/index”
  builds/ranger/power-soulbeast/index.md
Labels: netlify-cms/pending_publish

#803 Update Builds “revenant/condi-alac-renegade/index”
  builds/revenant/condi-alac-renegade/index.md
Labels: netlify-cms/pending_publish

#804 Update Builds “engineer/power-holosmith/index”
  builds/engineer/power-holosmith/index.md
Labels: netlify-cms/pending_publish

#805 Update Fractals “chaos-isles/index”
  fractals/chaos-isles/index.md
Labels: netlify-cms/pending_publish

#808 Update Fractals “cliffside/index”
  fractals/cliffside/index.md
Labels: netlify-cms/pending_publish

#807 Update Fractals “captain-mai-trin-boss/index”
  fractals/captain-mai-trin-boss/index.md
Labels: netlify-cms/pending_publish

#806 Update Fractals “aetherblade/index”
  fractals/aetherblade/index.md
Labels: netlify-cms/pending_publish

#815 Update Fractals “deepstone/index”
  fractals/deepstone/index.md
Labels: netlify-cms/pending_publish

#809 Update Fractals “snowblind/index”
  fractals/snowblind/index.md
Labels: netlify-cms/pending_publish

#810 Update Fractals “volcanic/index”
  fractals/volcanic/index.md
Labels: netlify-cms/pending_publish

#811 Update Fractals “uncategorized/index”
  fractals/uncategorized/index.md
Labels: netlify-cms/pending_publish

#812 Update Fractals “molten-boss/index”
  fractals/molten-boss/index.md
Labels: netlify-cms/pending_publish

#813 Update Fractals “swampland/index”
  fractals/swampland/index.md
Labels: netlify-cms/pending_publish

#814 Update Fractals “urban-battlegrounds/index”
  fractals/urban-battlegrounds/index.md
Labels: netlify-cms/pending_publish

#817 Update Fractals “sirens-reef/index”
  fractals/sirens-reef/index.md
Labels: netlify-cms/pending_publish

#816 Update Fractals “underground-facility/index”
  fractals/underground-facility/index.md
Labels: netlify-cms/pending_publish

#818 Update Fractals “sunqua-peak/index”
  fractals/sunqua-peak/index.md
Labels: netlify-cms/pending_review

#819 Update Fractals “volcanic/index”
  fractals/volcanic/index.md
Labels: netlify-cms/pending_publish

#821 Update Fractals “aetherblade/index”
  fractals/aetherblade/index.md
Labels: netlify-cms/pending_publish

#822 Update Fractals “molten-boss/index”
  fractals/molten-boss/index.md
Labels: netlify-cms/pending_publish

#823 Update Fractals “thaumanova-reactor/index”
  fractals/thaumanova-reactor/index.md
Labels: netlify-cms/pending_publish

#824 Update Builds “revenant/power-renegade/index”
  builds/revenant/power-renegade/index.md
Labels: netlify-cms/pending_publish
