Repository discretize/discretize-guides, pull requests merged in 2023-08, with the labels that each got.

#1344 Update Builds “necromancer/condi-scourge/index”
  builds/necromancer/condi-scourge/index.md
Labels: netlify-cms/pending_publish

#1345 Update Fractals “silent-surf/index”
  fractals/silent-surf/index.md
Labels: netlify-cms/pending_publish

#1346 Update Fractals “silent-surf/index”
  fractals/silent-surf/index.md
Labels: netlify-cms/pending_publish

#1348 Update Fractals “nightmare/index”
  fractals/nightmare/index.md
Labels: netlify-cms/pending_publish

#1349 Update Fractals “sunqua-peak/index”
  fractals/sunqua-peak/index.md
Labels: netlify-cms/pending_publish

#1351 Update Guides “new-player-guide/index”
  guides/new-player-guide/index.md
Labels: netlify-cms/pending_publish

#1353 Update Builds “necromancer/condi-scourge/index”
  builds/necromancer/condi-scourge/index.md
Labels: netlify-cms/pending_publish

#1354 Update Fractals “nightmare/index”
  fractals/nightmare/index.md
Labels: netlify-cms/pending_publish

#1355 Update Fractals “shattered-observatory/index”
  fractals/shattered-observatory/index.md
Labels: netlify-cms/pending_publish

#1356 Update Fractals “sunqua-peak/index”
  fractals/sunqua-peak/index.md
Labels: netlify-cms/pending_publish

#1357 Update Fractals “chaos-isles/index”
  fractals/chaos-isles/index.md
Labels: netlify-cms/pending_publish

#1358 Update Fractals “silent-surf/index”
  fractals/silent-surf/index.md
Labels: netlify-cms/pending_publish

#1359 Update Fractals “silent-surf/index”
  fractals/silent-surf/index.md
Labels: netlify-cms/pending_publish

#1360 Update Fractals “silent-surf/index”
  fractals/silent-surf/index.md
Labels: netlify-cms/pending_publish

#1363 Update Fractals “silent-surf/index”
  fractals/silent-surf/index.md
Labels: netlify-cms/pending_publish

#1364 Update Fractals “silent-surf/index”
  fractals/silent-surf/index.md
Labels: netlify-cms/pending_publish

#1365 Update Fractals “silent-surf/index”
  fractals/silent-surf/index.md
Labels: netlify-cms/pending_publish

#1366 Update Fractals “silent-surf/index”
  fractals/silent-surf/index.md
Labels: netlify-cms/pending_publish

#1380 Update Fractals “chaos-isles/index”
  fractals/chaos-isles/index.md
Labels: netlify-cms/draft

#1378 Update Fractals “captain-mai-trin-boss/index”
  fractals/captain-mai-trin-boss/index.md
Labels: netlify-cms/pending_review

#1377 Update Fractals “aetherblade/index”
  fractals/aetherblade/index.md
Labels: netlify-cms/pending_publish

#1379 Update Fractals “aquatic-ruins/index”
  fractals/aquatic-ruins/index.md
Labels: netlify-cms/pending_publish

#1381 Update Fractals “captain-mai-trin-boss/index”
  fractals/captain-mai-trin-boss/index.md
Labels: netlify-cms/pending_publish

#1383 Update Fractals “aetherblade/index”
  fractals/aetherblade/index.md
Labels: netlify-cms/pending_publish

#1384 Update Fractals “captain-mai-trin-boss/index”
  fractals/captain-mai-trin-boss/index.md
Labels: netlify-cms/pending_publish

#1385 Update Fractals “captain-mai-trin-boss/index”
  fractals/captain-mai-trin-boss/index.md
Labels: netlify-cms/pending_publish

#1390 Update Guides “teamcomp101/index”
  guides/teamcomp101/index.md
Labels: netlify-cms/pending_publish

#1391 Update Fractals “swampland/index”
  fractals/swampland/index.md
Labels: netlify-cms/pending_publish

#1392 Update Fractals “underground-facility/index”
  fractals/underground-facility/index.md
Labels: netlify-cms/pending_publish

#1393 Update Fractals “underground-facility/index”
  fractals/underground-facility/index.md
Labels: netlify-cms/pending_publish

#1394 Update Fractals “aetherblade/index”
  fractals/aetherblade/index.md
Labels: netlify-cms/pending_publish

#1382 Update Fractals “chaos-isles/index”
  fractals/chaos-isles/index.md
Labels: netlify-cms/pending_review
